root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  full_bin = "./tmp/server"
  include_ext = ["go", "html", "css", "js"]
  exclude_dir = ["tmp", "vendor", "node_modules", ".git"]
  exclude_regex = ["_test.go"]
  delay = 1000

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
